dados<-read.csv("household_power_consumption.txt",header = TRUE, sep = ";", colClasses = c(rep("character",9)), na.strings = "?")
x<-paste(dados$Date,dados$Time)
x<-strptime(x,format="%d/%m/%Y %H:%M:%S")
dados$Time<-x
dados$Date<-as.Date(dados$Date, format="%d/%m/%Y")
result<-subset(dados, Date %in% c(as.Date("2007/02/01"), as.Date("2007/02/02")))
result$Global_active_power <- sapply(result$Global_active_power, as.numeric)
result$Sub_metering_1 <- sapply(result$Sub_metering_1, as.numeric)
result$Sub_metering_2 <- sapply(result$Sub_metering_2, as.numeric)
result$Sub_metering_3 <- sapply(result$Sub_metering_3, as.numeric)
result$Voltage <- sapply(result$Voltage, as.numeric)
result$Global_reactive_power <- sapply(result$Global_reactive_power, as.numeric)
par(mfrow=c(2,2))
plot(result$Time, result$Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab="")
plot(result$Time, result$Voltage, type = "l", ylab = "Voltage", xlab="datetime")
plot(result$Time, result$Sub_metering_1, type = "l", col = "gray", ylab="Energy sub metering", xlab = "")
points(result$Time, result$Sub_metering_2, type = "l", col = "blue")
points(result$Time, result$Sub_metering_3, type = "l", col = "red")
legend("topright",cex = 0.1, col=c("gray","blue","red"),lty = c(1,1,1), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
plot(result$Time, result$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab="datetime")
dev.copy(png, "plot4.png")
dev.off()
